ex1: pi_serial.c pi_multi_thread.c

pi_serial: pi_serial.c
	g++ -o pi_serial pi_serial.c  -lpthread

pi_multi_thread: pi_multi_thread.c
	g++ -o pi_multi_thread pi_multi_thread.c -lpthread

clean:
	rm -f *.o ex1
